import type { Metadata } from "next";
import { Geist, Geist_Mono, Shadows_Into_Light } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import BgParticles from "@/components/common/particles";
import { ThemeProvider } from "next-themes";
import LenisProvider from "@/components/common/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const shadowsIntoLight = Shadows_Into_Light({
  subsets: ["latin"],
  weight: "400", // Shadows Into Light typically has only one weight (Regular)
  variable: "--font-shadows-into-light", // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Ansab Azys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${shadowsIntoLight.variable} dark:bg-[#0a0a0a] bg-[#f4f4f4] ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute="class" enableSystem={true}>
          <div className="fixed inset-0 z-0 w-full h-full overflow-hidden">
            <BgParticles />
          </div>
{/* 
          <div className="relative z-30">
            <Header />
          </div> */}

          <LenisProvider>{children}</LenisProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
